-- Phase 1 of the V1 redesign: additive schema foundations only.
-- No existing column is altered or removed, and nothing here changes any
-- current API/UI behavior — every new column is nullable or safely
-- defaulted so all existing rows (including Test Data) remain valid as-is.

-- Trainer -> Trainee relationship. Independent from department_id by
-- design: changing a user's department must never change their trainer,
-- and vice versa. Meaningful only for users whose role is Trainee;
-- enforced at the application layer, not via a DB constraint.
ALTER TABLE users ADD COLUMN trainer_id UUID REFERENCES users(id) ON DELETE SET NULL;
CREATE INDEX idx_users_trainer ON users(trainer_id);

-- Session invalidation on password reset (Phase 8 will use this, but it
-- lands now alongside the other user-table foundations).
ALTER TABLE users ADD COLUMN session_version INTEGER NOT NULL DEFAULT 1;

-- Device metadata + status + configurable passing score.
ALTER TABLE devices ADD COLUMN model TEXT;
ALTER TABLE devices ADD COLUMN purchase_date DATE;
ALTER TABLE devices ADD COLUMN warranty_expiry_date DATE;
ALTER TABLE devices ADD COLUMN image_path TEXT;
ALTER TABLE devices ADD COLUMN active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE devices ADD COLUMN passing_score INTEGER NOT NULL DEFAULT 80
  CHECK (passing_score BETWEEN 1 AND 100);

-- Non-destructive assignment lifecycle: due date + status instead of
-- relying on DELETE. Cancelling an assignment must preserve history.
ALTER TABLE assignments ADD COLUMN due_date TIMESTAMPTZ;
ALTER TABLE assignments ADD COLUMN status TEXT NOT NULL DEFAULT 'active'
  CHECK (status IN ('active', 'cancelled'));
ALTER TABLE assignments ADD COLUMN cancelled_at TIMESTAMPTZ;
ALTER TABLE assignments ADD COLUMN cancelled_by UUID REFERENCES users(id) ON DELETE SET NULL;

-- Replace the old blanket UNIQUE(user_id, device_id) with a partial
-- unique index that only applies to active rows, so a cancelled
-- assignment can coexist with a later re-assignment of the same pair
-- while every historical row is preserved. The old constraint's name is
-- looked up dynamically (rather than hardcoded) since it was
-- auto-generated by Postgres from the original inline UNIQUE in 001_init.sql.
DO $$
DECLARE
  cname text;
BEGIN
  SELECT tc.constraint_name INTO cname
  FROM information_schema.table_constraints tc
  WHERE tc.table_name = 'assignments'
    AND tc.constraint_type = 'UNIQUE';
  IF cname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE assignments DROP CONSTRAINT %I', cname);
  END IF;
END $$;

CREATE UNIQUE INDEX idx_assignments_active_unique ON assignments(user_id, device_id) WHERE status = 'active';
